version: '3'
services:
  mysql:
    ports:
      - "3306:3306"
    container_name: alt-bot-service
    command: --default-authentication-plugin=mysql_native_password
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: 'alt-bot'
    volumes:
      - ./data:/var/lib/mysql
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
volumes:
  data:
    driver: local